repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: check-yaml
  - id: trailing-whitespace
    files: (?x)^(
        config/make[.]inc[.\w]*|
        examples/example\d\d[-]?\w*/.+win
      )$
  - id: end-of-file-fixer
    files: (?x)^(
        config/make[.]inc[.\w]*|
        examples/example\d\d[-]?\w*/.+win
      )$
- repo: git://github.com/pseewald/fprettify
  rev: v0.3.3
  hooks:
  - id: fprettify
    args: ['--indent', '2']
    exclude: (?x)^(
        pwscf/.*
      )$
    verbose: true
