repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-yaml
    exclude: (?x)^(
        docs/mkdocs.yml
      )$
  - id: check-yaml
    name: check yaml unsafe
    args: ['--unsafe']
    files: (?x)^(
        docs/mkdocs.yml
      )$
  - id: trailing-whitespace
    files: (?x)^(
        config/make[.]inc[.\w]*|
        tutorials/tutorial\d\d[-]?\w*/.+win
      )$
  - id: end-of-file-fixer
    files: (?x)^(
        config/make[.]inc[.\w]*|
        tutorials/tutorial\d\d[-]?\w*/.+win
      )$
- repo: https://github.com/pseewald/fprettify
  rev: v0.3.3
  hooks:
  - id: fprettify
    args: ['--indent', '2']
    exclude: (?x)^(
        pwscf/.*
      )$
    verbose: true
- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.12.1
  hooks:
  - id: markdownlint-cli2
    args: ['--fix']
